# cluster.yaml - cluster configuration for my Snakefile.
__default__:
  partition: node
  time: '2:00:00'
  nodes: 1
  cores: 20

iterative_search:
  cores: 20
  time: '8:00:00'

realignment:
  cores: 10
  time: '2:00:00'

phylogeny:
  cores: 15
  time: '4:00:00'
