# cluster.yaml - cluster configuration for my Snakefile.
__default__:
  partition: node
  time: '2:00:00'
  cores: 5

iterative_search:
  cores: 20
  time: '8:00:00'

realignment:
  cores: 15
  time: '4:00:00'

phylogeny:
  cores: 20
  time: '30:00:00'
