sftp_address: "sftp.genewiz.com"
username: "isylvain_berkeley"
password: "aS06jJvl2oMG0MvKIBtx"

sftp_target_directory: "30-991411036/"
local_download_directory: "/groups/clinical/projects/Azenta_Data/30-991411036"
