"NextSeq 500/550 Mid Output": [re.compile("\w{4}AF\w{12}")]
"NextSeq 500/550 High Output": [re.compile("\w{4}BG\w{12}") re.compile("\w{4}AG\w{12}")]
"NextSeq 1000/2000 P1": [re.compile("\w{6}M5")]
"NextSeq 1000/2000 P2": [re.compile("\w{6}M5")]
"NextSeq 2000 P3": [re.compile("\w{6}HV")]
"HiSeq 2500 Rapid v2": [re.compile("\w{4}BC\w{12}")]
"HiSeq 2500 TruSeq v3": [re.compile("\w{4}AC\w{12}")]
"HiSeq 2500 High Output v4": [re.compile("\w{4}AN\w{12}")]
"HiSeq 3000/4000": [re.compile("\w{4}BB\w{12}")]
"HiSeq X": [re.compile("\w{4}AL\w{12}") re.compile("\w{4}CC\w{12}")]
"NovaSeq 6000 SP and S1": [re.compile("\w{4}DR\w{12}")]
"NovaSeq 6000 S2": [re.compile("\w{4}DM\w{12}")]
"NovaSeq 6000 S4": [re.compile("\w{4}DS\w{12}")]
"lane": [re.compile("L0{02}\d")]
"read": [re.compile("R[12]")]
"sample_name": [re.compile("IGU-\d{3}-N\d")]