# number of threads for multi-threaded applications
threads: 10

# Directory where the demultiplexed raw short reads are stored
#   *** In case the files are not demultiplexed, run: py/process_barcodes.py
# Biotite Path
read_directory: "/groups/doudna/projects/daniel_projects/doherty_ee/30-942700356/00_fastq"

# Biotite Path where the current analysis files will be stored
job_name: "/groups/doudna/projects/daniel_projects/doherty_ee/30-942700356_nt41"

# Path to reference sequence(s) to be used in te alignment
reference_path: "/groups/doudna/projects/daniel_projects/doherty_ee/30-942700356_wc/reference_seq"

# Trimmomatic
trim_params: "MINLEN:75"
