# Folder where input data is stored
input_dir: "/groups/doudna/projects/daniel_projects/prywes_n/input_data"

# File directory where files will be stored in
run: "/groups/doudna/projects/daniel_projects/prywes_n/rubisco_dms_75mid"

min_ident: '0.75'
site_offset: '3'

id_trim_instructions:


# Column names as displayed in the dms table
position_col: "Site"
enrichment_col: "5percent_CO2_20uM_IPTG"
aminoacid_col: "AminoAcid"
