# Folder where input data is stored
input_dir: "/groups/doudna/projects/daniel_projects/prywes_n/input_data"

threads: 20

# File directory where files will be stored in
run: "/groups/doudna/projects/daniel_projects/prywes_n/rubisco_dms_75mid"

min_ident: '0.75'
site_offset: '3'

experiment_id: ['rubisco_dms']

rax_path: "/home/danielbr/miniconda3/envs/rax/bin/raxmlHPC-PTHREADS-SSE3"


# Column names as displayed in the dms table
position_col: "Site"
enrichment_col: "5percent_CO2_20uM_IPTG"
aminoacid_col: "AminoAcid"
