# Folder where input data is stored
input_dir: "/groups/doudna/projects/daniel_projects/prywes_n/input_data"

# File directory where files will be stored in
run: "/groups/doudna/projects/daniel_projects/prywes_n/rubisco_dms"

# Column names as displayed in the dms table
position_col: "position"
enrichment_col: "Enrichment_mainCond"
aminoacid_col: "residue"
